plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-${project.mod_version}-mc${project.minecraft_version}"
}

repositories {
	mavenCentral()
	flatDir { dirs "libs" }
	maven { url "https://SILENCE-SIMSOOL.github.io/maven-repo/" }
	maven { url = uri("https://api.modrinth.com/maven") }
	maven { url = uri("https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1") }
}

loom {
	mods {
		"lucentclient" {
			sourceSet sourceSets.main
		}
	}

	runConfigs.named("client") {
		ideConfigGenerated = true
		property "devauth.enabled", "true"
		property "devauth.account", "main"
	}

    runConfigs.named("server") {
        ideConfigGenerated = false
    }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

 	modRuntimeOnly("me.djtheredstoner:DevAuth-fabric:${property("devauth_version")}")
 
	def lwjglVersion = project.property("minecraft_lwjgl_version")
	modImplementation "org.lwjgl:lwjgl-nanovg:${lwjglVersion}"
	include "org.lwjgl:lwjgl-nanovg:${lwjglVersion}"
	["windows", "linux", "macos", "macos-arm64"].each { os ->
		modImplementation "org.lwjgl:lwjgl-nanovg:${lwjglVersion}:natives-${os}"
		include "org.lwjgl:lwjgl-nanovg:${lwjglVersion}:natives-${os}"
	}

	def lucentVersion = "${project.lucent_version}-${project.minecraft_version}-${project.lucent_library}"
	modImplementation "com.github.SILENCE-SIMSOOL:lucent:${lucentVersion}"
	include "com.github.SILENCE-SIMSOOL:lucent:${lucentVersion}"
	
	modImplementation files("libs/SilenceUtils-1.0.0.jar")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.encoding = "UTF-8"
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {

	}
}